language: generic
sudo: required
services:
  - docker
env:
  global:
    # DOCKER_USERNAME
    - secure: "Pp8lv5N7PKemk0SXCT7DXftxivcx4gyrdQH6IKyXi05jwrpuOVlM3RBV72WAEoSxwtrA9UlThgyd/m7zixk2o8DxfI1nwpd4jFvlf3lJG+pVaDM3cGRyxhEz4JnMztMHz1hhiCY1yCIbuCoc9z2Wu3/bHYGhUbQC/1zwyNCoh2mUURjiAZZVmFGV/d79llm0aoX+zmEy16xbpmPr+imHpq4UAxdJtaBhl9PkHP3wPkskzPi9bi21ht1di//HRdkAjE9ZMsMcOjNx1J0QaIFfFsWScmPOVdQCiliouPl4kQIlziIHRcqK9wylRhUnIOwY/FEPcCmV13+0U8uNIqaM5JwQFGBYwmpHNLj9GT0lFRPuK3aomQCoDMs1heP0fmRcSGFZQfr2wU1Tj+wi2QImgxQuKmzf73+5tGK5sIgZ2BSMqcu+NCc4M8SN8TEa8evxFrrbaleTmE170TiZ90pthx5r2C0yETo46Nw30Fb+OwP3ittpDtaqm8hxIDZaJaQgMH8a84ZCgIIDPcrBNQKWOFaTSfft7ly02+PUJ1iIXU86+wsvgnWVqo5bIvnvYcPVFP6jJbfU8oSHlFRzulwMZDszOpZFQ0ZEoqSQK3xIerC3L7OSCkrypflpQTwF2ikxYR7L1iBQmQY7ZsFofyge4vKAgsFM3Oy0k8Y89mxOKiU="
    # DOCKER_PASSWORD
    - secure: "n+o4oYJ56UrSKR53Hecv5EpJvzmpAN45UhU6lLbJrD4UaF56GqLHMFEz9plo2JlJKXp/7kjz80mfia5BXWfOmOcq8xbmFcSGLi+6Vt1nyrr0rQ24kLoxoui6xpmJWvcEI4AJU5Fd4he3MSQHLRA4w4TcLVqHUDMPydX0/bKHvQYIN4XIKWw+sdtZiHYZ2FPtgDIKT8zM/Ll1uKFv7mYmjoNiO572l14PUCu5/iQVQMzgMdsAWh0C4TAkboCp6FygPR09PomH8NuQ03M1h9IM+PoI3RRoXUjoP0Vp1+cEX/ylxO13CUQOZrmin9hqcTi/T50/J1jP8t4oRPLIXWTNnCb2G7kYTAlWOVrRpkQyBm3eT4M7xgEXNQQwdAsahRhFdWPHZ/B4zVc3eey+TjG/l1uutQL99ryl3m6LPC00IMekgX9d8QJPSvrulvaeVOx2cdbMBjuBxcfAzz+YW2odHm+/bLuLA/i9sph8QwRo+yrmAzfVSDqUJ92WdAFbkFtUet4N12ZTIUwCpdBMGDJEwWfcDqAay0ik63XYTYHXDJCkIukZLn4gAa5Y3L2/3uESGtU2Ms8y5P+XFzdNzlZzSjo7Z1OO/Xs9O8NIz/JuUz8AkqNi2pSOkXpY/kHWe7sVtDvK1dIn5LWbBgN6+5lckD3+eLsKqrnkchTJ40ZN8Xw="
  matrix:
  - IMAGE=aws-ecr-cleaner
  # - IMAGE=fluentd-cloudwatch/0.12
  # - IMAGE=helm/2.7
  # - IMAGE=terraform-helm
  # - IMAGE=kubectl/1.8
  # - IMAGE=kops/1.8
  - IMAGE=kops/heptio-authenticator
  - IMAGE=openssl/1
  # - IMAGE=terraform-helm
  - IMAGE=boto3/1

script:
  - cd ${TRAVIS_BUILD_DIR}/${IMAGE} && make build 
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - cd ${TRAVIS_BUILD_DIR}/${IMAGE} && make publish

branches:
  only:
  - master
